### ISSUE TITLE
Reference orginal lists for sign in/out

### ISSUE THREAD

**Issue by trutzig89182** [misea/find-masto-folks#1]
Hey Mark, 
thanks again for your work. 

I would suggest that there is a link to the original pages in the lists subpages and information that you can find the modalities to sign out/in there. This would help to make sure that there is no confusion about you page copying the data.

In turn I think it would make sense to point to your page as a different mode to access the list and follow people. 

What do you think?

**Comment by misea** [comment]
I cleaned this up somewhat. There is now more explicit text if you browse a list and there's an info icon visible in phone view to show that same information.

<img width="801" alt="Screen Shot 2023-01-14 at 10 51 00 PM" src="https://user-images.githubusercontent.com/8292064/212527184-368f0874-3b1d-4972-aae2-eff1af13e01d.png">
